## Datenbereinigung des Datensatzes über das freie Rechtswissenschaftsuniversum im DACH Raum.

In [1]:
import pandas as pd

file = "2023-12-07 Datensatz.csv"
df = pd.read_csv(file, encoding="UTF8")

### Als erstes werden überflüssige Spalten, also solche ohne Eintrag entfernt.

In [2]:
df.dropna(axis=1, how='all', inplace = True)

### Dann wird manuell jeder Zeitschrift das entsprechende Land zugeordnet.

In [3]:
unique_abbr = df['Zeitschriftkürzel'].unique()

print('\nUnique Abbreviations:')
print(unique_abbr, len(unique_abbr))

Unique Abbreviations:
['Ajbals' 'BayZR' 'GB' nan 'EJELS' 'EALR' 'FoR' 'GJLE' 'GoJIL' 'GRZ' 'HFR'
 'JIPITEC' 'KrimOJ' 'JLL' 'OdW' 'MIR' 'MIP' 'ZRI' 'Rg' 'SPWR'
 'SutdZR-WissOn' 'VLR' 'EuZ' 'ZJS' 'ZVR'] 25

Ajbals - Oesterreich

BayZR - Deutschland

GB - Deutschland

Digital Recht - Deutschland (Kein Kürzel)

EJELS - Oesterreich

EALR - Oesterreich

FoR - Deutschland

GJLE - Deutschland

GoJIL - Deutschland

GRZ - Deutschland

HFR - Deutschland

JIPITEC - Deutschland

KrimOJ - Deutschland

JLL - Niederlande (englische Artikel)

OdW - Deutschland

MIR - Deutschland

MIP - Deutschland

ZRI - Deutschland

Rg - Deutschland

SPWR - Liechtenstein

SutdZR-WissOn - Deutschland (Achtung, wenn man Studentisches Forum für Recht und Gesellschaft googelt, findet man eine schweizer Zeitschrift. DIese ist allerdings aus Heidelberg)

VLR - Oesterreeich

EuZ - Schweiz

ZJS - Deutschland

ZIS - Deutschland (Zeitschrift für internationale Strafrechtsdogmatik - hat leider auch ZJS als Kürzel im Datensatz eingetragen)

ZVR - Deutschland (steht nirgendow exklusiv aber klingt so)

Zeitschrift für freiberufliche Künstler und Publizisten im Recht - Deutschland (Kein Kürzel)

### Jetzt erstmal gefundenen Fehler verbessern:

1. Zeitschrift für internationale Strafrechtsdogmatik richtiges Kürzel eintragen.

In [4]:
df[df['Zeitschrift'].str.contains('Zeitschrift für Internationale Strafrechtsdogmatik')][['Zeitschrift', 'Zeitschriftkürzel']]

                                            Zeitschrift Zeitschriftkürzel
7320  Zeitschrift für Internationale Strafrechtsdogm...               ZJS
7321  Zeitschrift für Internationale Strafrechtsdogm...               ZJS
7322  Zeitschrift für Internationale Strafrechtsdogm...               ZJS
7323  Zeitschrift für Internationale Strafrechtsdogm...               ZJS
7324  Zeitschrift für Internationale Strafrechtsdogm...               ZJS
...                                                 ...               ...
8909  Zeitschrift für Internationale Strafrechtsdogm...               ZJS
8910  Zeitschrift für Internationale Strafrechtsdogm...               ZJS
8911  Zeitschrift für Internationale Strafrechtsdogm...               ZJS
8912  Zeitschrift für Internationale Strafrechtsdogm...               ZJS
8913  Zeitschrift für Internationale Strafrechtsdogm...               ZJS

[1594 rows x 2 columns]

In [5]:
df.loc[df['Zeitschrift'].str.contains('Zeitschrift für Internationale Strafrechtsdogmatik'), 'Zeitschriftkürzel'] = 'ZIS'

df[df['Zeitschrift'].str.contains('Zeitschrift für Internationale Strafrechtsdogmatik')][['Zeitschrift', 'Zeitschriftkürzel']]

                                            Zeitschrift Zeitschriftkürzel
7320  Zeitschrift für Internationale Strafrechtsdogm...               ZIS
7321  Zeitschrift für Internationale Strafrechtsdogm...               ZIS
7322  Zeitschrift für Internationale Strafrechtsdogm...               ZIS
7323  Zeitschrift für Internationale Strafrechtsdogm...               ZIS
7324  Zeitschrift für Internationale Strafrechtsdogm...               ZIS
...                                                 ...               ...
8909  Zeitschrift für Internationale Strafrechtsdogm...               ZIS
8910  Zeitschrift für Internationale Strafrechtsdogm...               ZIS
8911  Zeitschrift für Internationale Strafrechtsdogm...               ZIS
8912  Zeitschrift für Internationale Strafrechtsdogm...               ZIS
8913  Zeitschrift für Internationale Strafrechtsdogm...               ZIS

[1594 rows x 2 columns]

In [6]:
Länderkürzel = "Ajbals - Österreich,BayZR - Deutschland,GB - Deutschland,Digital - Recht - Deutschland,(Kein Kürzel)EJELS - Österreich,EALR - Österreich,FoR - Deutschland,GJLE - Deutschland,GoJIL - Deutschland,GRZ - Deutschland,HFR - Deutschland,JIPITEC - Deutschland,KrimOJ - Deutschland,JLL - Niederlande,(englische Artikel)OdW - Deutschland,MIR - Deutschland,MIP - Deutschland,ZRI - Deutschland,Rg - Deutschland,SPWR - Liechtenstein,SutdZR-WissOn - Deutschland,(Achtung, wenn man Studentisches Forum für Recht und Gesellschaft googelt, findet man eine schweizer Zeitschrift. DIese ist allerdings aus Heidelberg)VLR - Österreich,EuZ - Schweiz,ZJS - Deutschland,ZIS - Deutschland,(Zeitschrift für internationale Strafrechtsdogmatik - hat leider auch ZJS als Kürzel im Datensatz eingetragen)ZVR - Deutschland,(steht nirgendow exklusiv aber klingt so)Zeitschrift für freiberufliche Künstler und Publizisten im Recht - Deutschland (Kein Kürzel)"

# Remove parts of the string within brackets
output_string = ''
inside_brackets = False

for char in Länderkürzel:
    if char == '(':
        inside_brackets = True
    elif char == ')':
        inside_brackets = False
    elif not inside_brackets:
        output_string += char

output_string

output_list = output_string.split(',')

final_list = []
for entry in output_list:
  kv = entry.split(' - ')
  final_list.append(kv)

final_list[3] = ['Digital - Recht', 'Deutschland']

final_list

[['Ajbals', 'Österreich'],
 ['BayZR', 'Deutschland'],
 ['GB', 'Deutschland'],
 ['Digital - Recht', 'Deutschland'],
 ['EJELS', 'Österreich'],
 ['EALR', 'Österreich'],
 ['FoR', 'Deutschland'],
 ['GJLE', 'Deutschland'],
 ['GoJIL', 'Deutschland'],
 ['GRZ', 'Deutschland'],
 ['HFR', 'Deutschland'],
 ['JIPITEC', 'Deutschland'],
 ['KrimOJ', 'Deutschland'],
 ['JLL', 'Niederlande'],
 ['OdW', 'Deutschland'],
 ['MIR', 'Deutschland'],
 ['MIP', 'Deutschland'],
 ['ZRI', 'Deutschland'],
 ['Rg', 'Deutschland'],
 ['SPWR', 'Liechtenstein'],
 ['SutdZR-WissOn', 'Deutschland'],
 ['VLR', 'Österreich'],
 ['EuZ', 'Schweiz'],
 ['ZJS', 'Deutschland'],
 ['ZIS', 'Deutschland'],
 ['ZVR', 'Deutschland'],
 ['Zeitschrift für freiberufliche Künstler und Publizisten im Recht',
  'Deutschland ']]

Jetzt die Ländernamen den einzelnen Einträgen zuordnen

In [7]:
import numpy as np

df['Land'] = '-'

for entry in final_list:
  df.loc[df['Zeitschrift'].str.contains(entry[0]) | df['Zeitschriftkürzel'].str.contains(entry[0]), 'Land'] = entry[1]

df.head()

,Autor ohne Grad,Autor mit Grad,Titel,Untertitel,Zeitschrift,Zeitschriftkürzel,Volume,Issue,Datum,Seitennummer,PDF vom Artikel (Druckversion) (Link),PDF vom Artikel (Digitalversion) (Link),DOI vom Artikel,Bildschirmansicht vom Artikel (Link),Abstract von der Gesamtausgabe (Bildschirmansicht) (Link),PDF_Gesamtausgabe_Link_Druck,Abstract vom Artikel,Rubrik,Gesamtausgabe (Bildschirmansicht) (Link),Land
0,Abdulelah Alsahli,NaN,Challenges towards selecting Saudi Arabia as a...,NaN,"Academic Journal of Business, Administration, ...",Ajbals,Vol. 9 No. 2 - July 2023,NaN,NaN,NaN,https://iipccl.org/wp-content/uploads/2023/09/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Österreich
1,"Endri Papajorgji, Artela Roshi",NaN,ECJ Case 27/76 United Brands v Commission and ...,NaN,"Academic Journal of Business, Administration, ...",Ajbals,Vol. 9 No. 2 - July 2023,NaN,NaN,NaN,https://iipccl.org/wp-content/uploads/2023/09/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Österreich
2,"Jonida Gjuzi-Bushi, Ema Kristo",NaN,Didactics of intercultural communication and b...,NaN,"Academic Journal of Business, Administration, ...",Ajbals,Vol. 9 No. 2 - July 2023,NaN,NaN,NaN,https://iipccl.org/wp-content/uploads/2023/09/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Österreich
3,Lindita Kiri,NaN,Demographic transition - Global population pat...,NaN,"Academic Journal of Business, Administration, ...",Ajbals,Vol. 9 No. 2 - July 2023,NaN,NaN,NaN,https://iipccl.org/wp-content/uploads/2023/09/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Österreich
4,"Lena Hoffman, Endri Papajorgji, ,",NaN,About the Journal,NaN,"Academic Journal of Business, Administration, ...",Ajbals,Vol. 9 No. 1 - March 2023,NaN,NaN,NaN,https://iipccl.org/wp-content/uploads/2023/06/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Österreich

In [8]:
df[df['Land'].str.contains('-')].count()

Autor ohne Grad                                              0
Autor mit Grad                                               0
Titel                                                        0
Untertitel                                                   0
Zeitschrift                                                  0
Zeitschriftkürzel                                            0
Volume                                                       0
Issue                                                        0
Datum                                                        0
Seitennummer                                                 0
PDF vom Artikel (Druckversion) (Link)                        0
PDF vom Artikel (Digitalversion) (Link)                      0
DOI vom Artikel                                              0
Bildschirmansicht vom Artikel (Link)                         0
Abstract von der Gesamtausgabe (Bildschirmansicht) (Link)    0
PDF_Gesamtausgabe_Link_Druck                                 0
Abstract vom Artikel                                         0
Rubrik                                                       0
Gesamtausgabe (Bildschirmansicht) (Link)                     0
Land                                                         0
dtype: int64

In [9]:
df['Volume'][~df['Volume'].isna()]

0        Vol. 9 No. 2 - July 2023
1        Vol. 9 No. 2 - July 2023
2        Vol. 9 No. 2 - July 2023
3        Vol. 9 No. 2 - July 2023
4       Vol. 9 No. 1 - March 2023
                  ...
5070                     Articles
5071                Vol. 1 (2017)
5072                     Articles
5073                Vol. 1 (2017)
5074                     Articles
Name: Volume, Length: 1811, dtype: object

In [10]:
df['Datum'][~df['Datum'].isna()]

648     Veröffentlicht:Oct 16, 2023
650     Veröffentlicht:Oct 16, 2023
652     Veröffentlicht:Oct 16, 2023
654     Veröffentlicht:Oct 16, 2023
656     Veröffentlicht:Oct 16, 2023
                   ...
3236                     2023-05-19
3237                     2023-05-19
3238                     2023-05-19
3239                     2023-05-19
3240                     2023-05-19
Name: Datum, Length: 585, dtype: object

In [11]:
unique_abbr = df['Zeitschriftkürzel'].unique()

print('\nUnique Abbreviations:')
print(unique_abbr, len(unique_abbr))

Unique Abbreviations:
['Ajbals' 'BayZR' 'GB' nan 'EJELS' 'EALR' 'FoR' 'GJLE' 'GoJIL' 'GRZ' 'HFR'
 'JIPITEC' 'KrimOJ' 'JLL' 'OdW' 'MIR' 'MIP' 'ZRI' 'Rg' 'SPWR'
 'SutdZR-WissOn' 'VLR' 'EuZ' 'ZJS' 'ZIS' 'ZVR'] 26

In [12]:
df[['Zeitschrift', 'Zeitschriftkürzel']].groupby('Zeitschrift').count().sort_values('Zeitschriftkürzel', ascending=False)

                                                    Zeitschriftkürzel
Zeitschrift
Zeitschrift für das Juristische Studium                          1919
Zeitschrift für Internationale Strafrechtsdogmatik               1594
Rechtsgeschichte – Legal History                                 1276
Academic Journal of Business, Administration, L...                605
European Journal of Economics, Law and Social S...                486
Zeitschrift für Europarecht                                       371
Ordnung der Wissenschaft                                          364
J. of Intellectual Property, Information Techno...                360
Zeitschrift für Verwaltungsrecht Online                           280
Zeitschrift für Recht & Islam                                     272
Zeitschrift für Parteienwissenschaften                            219
Humboldt Forum Recht                                              195
Forum Recht                                                       193
Göttinger Rechtszeitschrift                                       139
Spektrum des Wirtschaftsrechts                                    136
Studentisches Forum für Recht und Gesellschaft                    130
Der Grüne Bote                                                    110
ELSA Austria Law Review                                            90
Kriminologie - Das Online-Journal                                  81
Bayreuther Zeitschrift Für Rechtswissenschaft                      70
Medien Internet und Recht                                          69
Goettingen J. of International Law                                 67
International J. of Language & Law                                 57
University of Vienna Law Review                                    45
Academic Journal of Business, Administration, L...                 42
Sonderausgabe »Nationalsozialistisches Strafrecht«                  5
German J. of Legal Education                                        5
Digital - Recht                                                     0
Zeitschrift für freiberufliche Künstler und Pub...                  0

### Something is wrong with Digital - Recht and Zeitschrift für freiberufliche Künstler und Publizisten im Recht 

After looking them up we noticed, that the Zeitschrift für freiberufliche Künstler und Publizisten im Recht didn't have actual entries and Digital - Recht was just missing a abbreviation. So we removed the entries for Zeitschrift für freiberufliche Künstler und Publizisten im Recht and added an abbreviation (D-R).

In [13]:
df[['Titel', 'Zeitschrift']][df['Zeitschriftkürzel'].isna()]

,Titel,Zeitschrift
827,Der Einsatz Digitaler Agenten im Rechtsverkehr,Digital - Recht
828,Information aus der Blackbox: Zum Verhältnis v...,Digital - Recht
829,Interessenwahrnehmung durch fremdnützige Daten...,Digital - Recht
830,Rechte an Forschungsdaten,Digital - Recht
831,Diskriminierungsfreie KI,Digital - Recht
832,Informatische Modellierung rechtlichen Denkens...,Digital - Recht
833,Auskunftsansprüche gegen Diensteanbieter der I...,Digital - Recht
834,Die urheberrechtliche Verantwortlichkeit für n...,Digital - Recht
835,Software als Beweiswerkzeug: Gerichtliche Sach...,Digital - Recht
836,Recht im Register – Register im Recht: Eine ve...,Digital - Recht
837,Rechtsdurchsetzende nichtanwaltliche Dienstlei...,Digital - Recht
838,Fernkontrolle im Internet der Dinge,Digital - Recht
839,Einführung in das Technikrecht,Digital - Recht
840,Gewährleistung 4.0: Rechtliche Herausforderung...,Digital - Recht
9194,NaN,Zeitschrift für freiberufliche Künstler und Pu...
9195,NaN,Zeitschrift für freiberufliche Künstler und Pu...
9196,NaN,Zeitschrift für freiberufliche Künstler und Pu...
9197,NaN,Zeitschrift für freiberufliche Künstler und Pu...
9198,NaN,Zeitschrift für freiberufliche Künstler und Pu...
9199,NaN,Zeitschrift für freiberufliche Künstler und Pu...
9200,NaN,Zeitschrift für freiberufliche Künstler und Pu...
9201,NaN,Zeitschrift für freiberufliche Künstler und Pu...
9202,NaN,Zeitschrift für freiberufliche Künstler und Pu...
9203,NaN,Zeitschrift für freiberufliche Künstler und Pu...
9204,NaN,Zeitschrift für freiberufliche Künstler und Pu...
9205,NaN,Zeitschrift für freiberufliche Künstler und Pu...
9206,NaN,Zeitschrift für freiberufliche Künstler und Pu...
9207,NaN,Zeitschrift für freiberufliche Künstler und Pu...
9208,NaN,Zeitschrift für freiberufliche Künstler und Pu...

In [14]:
df['Zeitschriftkürzel'][df['Zeitschrift'] == 'Digital - Recht'] = 'D-R'

In [15]:
df[['Titel', 'Zeitschrift']][df['Zeitschriftkürzel'].isna()]

     Titel                                        Zeitschrift
9194   NaN  Zeitschrift für freiberufliche Künstler und Pu...
9195   NaN  Zeitschrift für freiberufliche Künstler und Pu...
9196   NaN  Zeitschrift für freiberufliche Künstler und Pu...
9197   NaN  Zeitschrift für freiberufliche Künstler und Pu...
9198   NaN  Zeitschrift für freiberufliche Künstler und Pu...
9199   NaN  Zeitschrift für freiberufliche Künstler und Pu...
9200   NaN  Zeitschrift für freiberufliche Künstler und Pu...
9201   NaN  Zeitschrift für freiberufliche Künstler und Pu...
9202   NaN  Zeitschrift für freiberufliche Künstler und Pu...
9203   NaN  Zeitschrift für freiberufliche Künstler und Pu...
9204   NaN  Zeitschrift für freiberufliche Künstler und Pu...
9205   NaN  Zeitschrift für freiberufliche Künstler und Pu...
9206   NaN  Zeitschrift für freiberufliche Künstler und Pu...
9207   NaN  Zeitschrift für freiberufliche Künstler und Pu...
9208   NaN  Zeitschrift für freiberufliche Künstler und Pu...

In [16]:
df.drop(df[df['Zeitschrift'] == 'Zeitschrift für freiberufliche Künstler und Publizisten im Recht'].index, inplace=True)

In [17]:
df[['Titel', 'Zeitschrift']][df['Zeitschriftkürzel'].isna()]

Empty DataFrame
Columns: [Titel, Zeitschrift]
Index: []

In [18]:
df.to_csv('aufgeräumter_Datensatz.csv', index=False)

combine columns 'Autor mit Grad' and 'Autor ohne Grad'

In [19]:
df['all_authors'] = df['Autor ohne Grad'].str.cat(df['Autor mit Grad'], sep='', na_rep='?')
df['all_authors']

0                       Abdulelah Alsahli?
1          Endri Papajorgji, Artela Roshi?
2          Jonida Gjuzi-Bushi, Ema Kristo?
3                            Lindita Kiri?
4       Lena Hoffman, Endri Papajorgji, ,?
                       ...
9189                                    ??
9190                                    ??
9191                                    ??
9192                                    ??
9193                                    ??
Name: all_authors, Length: 9194, dtype: object

In [20]:
df['all_authors'] = df['all_authors'].str.replace('?', '', regex=False)
df['all_authors']

0                       Abdulelah Alsahli
1          Endri Papajorgji, Artela Roshi
2          Jonida Gjuzi-Bushi, Ema Kristo
3                            Lindita Kiri
4       Lena Hoffman, Endri Papajorgji, ,
                      ...
9189
9190
9191
9192
9193
Name: all_authors, Length: 9194, dtype: object

# Prepare dataset to build a treemap

The structure (columns) needed is country (Land) -> journal (Zeitschrift, Zeitschriftkürzel) -> title (Titel)

We can use the abbreviation of the journal name to display and the full journal name as a tooltip.

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9194 entries, 0 to 9193
Data columns (total 21 columns):
 #   Column                                                     Non-Null Count  Dtype
---  ------                                                     --------------  -----
 0   Autor ohne Grad                                            8154 non-null   object
 1   Autor mit Grad                                             2026 non-null   object
 2   Titel                                                      9089 non-null   object
 3   Untertitel                                                 407 non-null    object
 4   Zeitschrift                                                9194 non-null   object
 5   Zeitschriftkürzel                                          9194 non-null   object
 6   Volume                                                     1811 non-null   object
 7   Issue                                                      139 non-null    object
 8   Datum                                                      585 non-null    object
 9   Seitennummer                                               634 non-null    object
 10  PDF vom Artikel (Druckversion) (Link)                      6116 non-null   object
 11  PDF vom Artikel (Digitalversion) (Link)                    2082 non-null   object
 12  DOI vom Artikel                                            446 non-null    object
 13  Bildschirmansicht vom Artikel (Link)                       1927 non-null   object
 14  Abstract von der Gesamtausgabe (Bildschirmansicht) (Link)  70 non-null     object
 15  PDF_Gesamtausgabe_Link_Druck                               5 non-null      object
 16  Abstract vom Artikel                                       1041 non-null   object
 17  Rubrik                                                     661 non-null    object
 18  Gesamtausgabe (Bildschirmansicht) (Link)                   434 non-null    object
 19  Land                                                       9194 non-null   object
 20  all_authors                                                9194 non-null   object
dtypes: object(21)
memory usage: 1.5+ MB

In [22]:
baumkarte_df = df.drop(['Autor mit Grad', 'Autor ohne Grad', 'Untertitel', 'Volume', 'Issue', 'Datum', 'Seitennummer', 'PDF vom Artikel (Druckversion) (Link)', 'PDF vom Artikel (Digitalversion) (Link)', 'DOI vom Artikel', 'Bildschirmansicht vom Artikel (Link)', 'Abstract von der Gesamtausgabe (Bildschirmansicht) (Link)', 'PDF_Gesamtausgabe_Link_Druck', 'Abstract vom Artikel', 'Rubrik', 'Gesamtausgabe (Bildschirmansicht) (Link)', 'all_authors'], axis = 1)
baumkarte_df.to_csv('Baumkarte_Datensatz.csv', index=False)

In [23]:
baumkarte_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9194 entries, 0 to 9193
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Titel              9089 non-null   object
 1   Zeitschrift        9194 non-null   object
 2   Zeitschriftkürzel  9194 non-null   object
 3   Land               9194 non-null   object
dtypes: object(4)
memory usage: 287.4+ KB

lets find the data without a title, and wether they are useful entries.

In [24]:
baumkarte_df[baumkarte_df['Titel'].isnull()]

,Titel,Zeitschrift,Zeitschriftkürzel,Land
1610,NaN,German J. of Legal Education,GJLE,Deutschland
1611,NaN,German J. of Legal Education,GJLE,Deutschland
1612,NaN,German J. of Legal Education,GJLE,Deutschland
1613,NaN,German J. of Legal Education,GJLE,Deutschland
1614,NaN,German J. of Legal Education,GJLE,Deutschland
...,...,...,...,...
7219,NaN,Zeitschrift für das Juristische Studium,ZJS,Deutschland
7239,NaN,Zeitschrift für das Juristische Studium,ZJS,Deutschland
7260,NaN,Zeitschrift für das Juristische Studium,ZJS,Deutschland
7285,NaN,Zeitschrift für das Juristische Studium,ZJS,Deutschland
7302,NaN,Zeitschrift für das Juristische Studium,ZJS,Deutschland

In [25]:
cleaneddf = baumkarte_df.dropna(subset=['Titel'])
#cleaneddf = df.drop([1610, 1611, 1612, 1613, 1614, 1615])
cleaneddf.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9089 entries, 0 to 9193
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Titel              9089 non-null   object
 1   Zeitschrift        9089 non-null   object
 2   Zeitschriftkürzel  9089 non-null   object
 3   Land               9089 non-null   object
dtypes: object(4)
memory usage: 355.0+ KB

In [26]:

cleaneddf.loc[cleaneddf['Zeitschrift'] == 'Academic Journal of Business, Administration, Law and Social Sciences (Austria) E-ISSN 2410-8693 / ISSN 2410-3918', 'Zeitschrift'] = 'Academic Journal of Business, Administration, Law and Social Sciences'
cleaneddf.loc[cleaneddf['Zeitschrift'] == 'Academic Journal of Business, Administration, Law and Social Sciences E-ISSN 2410-8693 / ISSN 2410-3918', 'Zeitschrift'] = 'Academic Journal of Business, Administration, Law and Social Sciences'

cleaneddf.to_csv('Baumkarte_Datensatz.csv', index=False)